Feature/windowtonavigationwindow
DLC-Sharp2017/LiquidVassel pull request #22
Opened 2017-05-31 12:06 UTC by fredHwilliams

2017-05-31 13:15 UTC, frederic34 approved these changes

2017-05-31 15:14 UTC, viasisco requested changes

2017-05-31 15:14 UTC, viasisco commented on LiquidVassel/LoginWindow.xaml
> +        <Image Source="C:\Users\34011-36-04\Source\Repos\LiquidVassel\LiquidVassel\images\vesselLogin.jpg"/>
il faut que le chemin soit relatif et non absolu

2017-06-01 08:17 UTC, viasisco approved these changes

2017-06-01 08:18 UTC, merged